server:
  port: 8070

# dubbo的基本信息
dubbo:
  application:
    name: user-service
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: dubbo
    port: 9991

# jdbc
spring:
  datasource:
    password: 1111
    username: root
    url: jdbc:mysql://localhost:3306/gmall_db?serverTimezone=UTC&characterEncoding=UTF-8
