server:
  port: 8071

# dubbo的基本信息
dubbo:
  application:
    name: manage-service
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: dubbo
    port: 9992


# jdbc
spring:
  datasource:
    password: 1111
    username: root
    url: jdbc:mysql://localhost:3306/gmall_db?serverTimezone=UTC&characterEncoding=UTF-8
#启动驼峰式
# user_name ---> userName
mybatis:
  configuration:
    map-underscore-to-camel-case: true
